### ISSUE TITLE
Silent mode in command line

### ISSUE THREAD

**Issue by SuperDizor** [winseros/pboman3#22]
Would be fun to have an option to prevent UI from opening when we use command line.
Thanks

**Comment by winseros** [comment]
You mean - a "console-like" variant of pack/unpack?

**Comment by SuperDizor** [comment]
Currently, I use a batch file for packing my pbos.

`pbom.exe pack <folder> -o <outputfile>`

When this command is done, we need to click <Close> then the script continues. I mean a way to prevent this window to open and remove the user action to the script.

**Comment by winseros** [comment]
I understand. Give me some time.

**Comment by winseros** [comment]
@SuperDizor could you check the [v1.3.0](https://github.com/winseros/pboman3/releases/tag/v1.3.0) release?

I [added](https://github.com/winseros/pboman3/blob/cba115b00c706dce7a40c5216af5892542ce7aa3/pbom/commandline.h#L76) the `-u`/`--no-ui` option.

**Comment by SuperDizor** [comment]
@winseros I've try with the new version (v1.3.0) but it doesn't work. I reinstall completely the software.

I try those commands:
-  `pbom.exe --no-ui pack <folder> -o <outputfile>`
-  `pbom.exe pack <folder> --no-ui -o <outputfile>`
-  `pbom.exe pack <folder> -o <outputfile> --no-ui`

Did I miss something ?

**Comment by winseros** [comment]
> but it doesn't work

I think the core problem is the application prints nothing to console. This is the drawback of the GUI executable - it can't use console output. And if you misspell a name of a file or directory or made a command line mistake - it silently fails.

I think this problem can be solved only by making a dedicated executable file for the console operations.

Again, give me some time :)

**Comment by winseros** [comment]
I added the dedicated executable `pboc.exe` for the console usage. It has almost the same set of commands, but it can print its output to console. So a user would see what's going on.

Could you please check the artifacts from the [#70](https://github.com/winseros/pboman3/actions/runs/2054066717) build? If they work as expected, I'll promote them to a release.

**Comment by winseros** [comment]
@SuperDizor ?

**Comment by SuperDizor** [comment]
Sorry for the delay. Looks good to me. Thank you very much!

**Comment by winseros** [comment]
Nice. I'll promote the build to the release then.

**Comment by winseros** [comment]
Created the [1.4.0 release](https://github.com/winseros/pboman3/releases/tag/v1.4.0)
