### ISSUE TITLE
Packing into PBO is causing mission not to start

### ISSUE THREAD

**Issue by Gryphon95** [winseros/pboman3#23]
I'm trying to unpack an Antistasi pbo and then repacking loses 4mb of data and causes the mission to no longer start I can provide any files

**Comment by winseros** [comment]
>  I can provide any files

Kindly provide the PBO you work with.

**Comment by Gryphon95** [comment]
[here](https://drive.google.com/file/d/1qr4gGnAOZkfWM0xFgUROkXj1vivgVO7i/view?usp=sharing) is the original, [here](https://drive.google.com/file/d/1-lrfq6waZfozdKKniGGPtTBwdc59q21c/view?usp=sharing) is what i get after packing, and [here](url) is what I get with unpacking.

**Comment by winseros** [comment]
I explored both PBOs. They differ only by a single file: `cba_settings.sqf`. The files are totally different, but none of them looks broken. 

So I'd like to know, if you just unpacked/repacked the PBO, or also changed any files?

**Comment by Gryphon95** [comment]
All that I changed was the cba_settings.sqf

**Comment by winseros** [comment]
So any chance the script might cause the mission not to start? What is the exact error?

**Comment by winseros** [comment]
Could you check artifacts from the build [#70](https://github.com/winseros/pboman3/actions/runs/2054066717)? I added a dedicated executable `pboc.exe` for command-line usage. If the executable works fine, I'll promote it to a release.

**Comment by winseros** [comment]
Closing as there is no feedback from the author
