### ISSUE TITLE
PBO Manager halving the file size 

### ISSUE THREAD

**Issue by Raideralexis** [winseros/pboman3#26]
I'm trying to edit a mission but when it's time to repack it, pbo manager halves the size of the pbo. Using your old pbo manager doesn't seem to cause any problems..

.

**Comment by Raideralexis** [comment]
> I'm trying to edit a mission but when it's time to repack it, pbo manager halves the size of the pbo. Using your old pbo manager doesn't seem to cause any problems..
> 
> .
![Error1](https://user-images.githubusercontent.com/28113905/167027594-1c5a6f41-8e42-4962-bf46-bb6aa1cd6560.PNG)

![Captura](https://user-images.githubusercontent.com/28113905/167027602-14419e92-9182-4fb8-b347-d96cefe563fd.PNG)

**Comment by winseros** [comment]
The previous version did not apply file compression, while the new one - does.
Please let me know whether the new file still functional despite the reduced size.

**Comment by logimy** [comment]
> Please let me know whether the new file still functional despite the reduced size.
No, it doesn't. I've tried to repack Antistasi into PBO file with compression and mission has stopped working correctly.

**Comment by winseros** [comment]
Can you share the original file and the repacked one?

**Comment by winseros** [comment]
Hi, @stubbornick. Now I see this strange behavior, though can not understand its origin yet.

For some reason, after applying compression to `.sqf` scripts, they refuse being `execVM`-ed. Though they still perfectly get `call`-ed and `spawn`-ed.

As a workaround, you may disable compression while packaging. For that, you put a file with the `pbo.json` in the mission root. The file content should be:

```
{
    "compress": {
        "exclude": [
        ],
        "include": [
        ]
    },
    "headers": [
    ]
}
```
You may ensure the compression got disabled by looking at the pbo size.

Meanwhile I'll try to figure out why compression makes ArmA so strangely "partially-crazy".

**Comment by khmelev77** [comment]
i have some problem with Arma 3 Domination mission (altis map)
After compression revive (if player is killed) in mission not working

**Comment by winseros** [comment]
I think it worth disabling compression of sqf by-default.

**Comment by Nighthawk42** [comment]
> I think it worth disabling compression of sqf by-default.

I concur. Until I found the JSON excludes, I too kept having my missions halved and they'd break around 80% of the time. Compression is nice, but in this day and age of mass storage might make it fairly moot unless you have hundreds of PBOs making up a addon or such.

**Comment by winseros** [comment]
I disabled the default script compression.
