### ISSUE TITLE
No window promt when packing/unpacking PBO via context menu

### ISSUE THREAD

**Issue by m1kesk** [winseros/pboman3#28]
When I unpack mission or addon, it shows me this promt, that it is done and I need to click on button "Close" or click "X" to close it.
Please remove this prompt in completion.

Show it only, if there is a problem with unpacking.
Make a setting in software to disable/enable prompt on completion.

[https://images2.imgbox.com/84/ab/110zsfVD_o.png](https://images2.imgbox.com/84/ab/110zsfVD_o.png)

**Comment by winseros** [comment]
Try using `pboc.exe` instead of `pbom.exe`. It should do the trick.

**Comment by m1kesk** [comment]
How can I setup application to use `pboc.exe` when unpacking via context menu? I am usually unpacking via right click on mission PBO and selecting unpack via context menu.

[https://imgbox.com/pBxNuUrg](https://imgbox.com/pBxNuUrgl)

**Comment by winseros** [comment]
Ah, I thought you were trying to use it via a script. Did not get, you mean unpacking with the context menu. I'll see what I can do, but I can't promise to do it in a short term.

**Comment by m1kesk** [comment]
would be nice if for both packing and unpacking action

**Comment by winseros** [comment]
Implemented in [v1.6.0](https://github.com/winseros/pboman3/releases/tag/v1.6.0)
