### ISSUE TITLE
Program crashes when opening an mangled mikero 9.11 PBO

### ISSUE THREAD

**Issue by hurtosera** [winseros/pboman3#29]
When the program tries to open a mangled PBO with the latest version of Mikero (DePbo.dll.9.11), the program crashes and then a .dmp appears in the system CrashDumps folder.

If you need any PBO to test it, do not hesitate to contact me.

**Comment by winseros** [comment]
Hi, please share a PBO file - it will be very helpful.

**Comment by hurtosera** [comment]
Check your email, I'll send it to you there

**Comment by winseros** [comment]
I found what's wrong - the pbo contains files named `//` the app wasn't prepared for. Will fix.

**Comment by winseros** [comment]
Hi. Please try the [#104](https://github.com/winseros/pboman3/actions/runs/3928076932) build. If it works, I'll promote it to a release.

**Comment by hurtosera** [comment]
I was able to open these types of files but when trying to extract them the program crashes.
Another problem I had was with the installer, since when I installed the new version (I had previously uninstalled the other one), when I restarted the computer, the Windows file explorer crashed, so I had to uninstall the program and run it from the compressed all the dll, exe and others are already there

**Comment by winseros** [comment]
What is your environment? I tried it on my `Windows 10` and it did not gie any troubles.

**Comment by winseros** [comment]
Great. Will make a release based on it then. Thank you!
