### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by JasperRab** [winseros/pboman3#33]
There is an spelling error under View, see picture below.

![image](https://user-images.githubusercontent.com/12704305/230888128-020811a8-95d9-43aa-a731-945ae444794c.png)

**Comment by winseros** [comment]
Hi, thanks for noticing. I'll fix in the next release.

**Comment by winseros** [comment]
Resolved in [v1.6.0](https://github.com/winseros/pboman3/releases/tag/v1.6.0)
