### ISSUE TITLE
File extraction doesn't work.

### ISSUE THREAD

**Issue by Apricot-ale** [winseros/pboman3#35]
File extraction does not work properly on Ver 1.5.0.
pbo.json is generated when perform extraction.
Installation destination is local. (Just for me)

Ver 1.4.1 can be extraction correctly. 
also extract it with Mikero's ExtractPbo is without any problems.

Maybe the latest Windows 10 update is the culprit. I recently did a clean install of Windows 10.
Edition/Version: Windows 10 Home 22H2 built 19045.2913

pbo.json contents is below.
`{
    "compress": {
        "exclude": [
        ],
        "include": [
        ]
    },
    "headers": [
        {
            "name": "prefix",
            "value": "myaddonname"
        }
    ]
}
`

**Comment by winseros** [comment]
Hi, could you provide more details?

**Comment by Apricot-ale** [comment]
Sorry, solved.
It seems that the "only json is generated" problem occurs only when there is only config.bin (config.cpp) in pbo.

**Comment by winseros** [comment]
The issue might be the duplicate of #32
