### ISSUE TITLE
Unable to open some PBOs. Missions and addons

### ISSUE THREAD

**Issue by ilbinek** [winseros/pboman3#36]
Hey there, I am not able to open some PBOs. These are missions and addons, all of them working fine in Arma and I am able to open them with other PBO tools like the old PBO manager.

Where would I send the PBOs for you to test and hopefully come up with a fix if possible?

**Comment by winseros** [comment]
Hi, is there a sample PBO?

**Comment by ilbinek** [comment]
The mission pbo can be downloaded here: https://tbdevent.eu/wog_184_slomannaya_strela_11.UMB_Colombia.pbo
As for the addon, one of them is PLS Armored Vehicles Pack https://steamcommunity.com/sharedfiles/filedetails/?id=2578187969
But the basic Arma pbos in Addons folder also can't be opened and with the older version of PBO Manager they can be.
The one friend used to open those is PBOManager v.1.4 beta
![image](https://user-images.githubusercontent.com/23197934/236900774-d1698b4d-ff09-4201-a7a3-a063ddd93875.png)

**Comment by winseros** [comment]
May you try the [#123](https://github.com/winseros/pboman3/actions/runs/4651896400) build?

**Comment by ilbinek** [comment]
> 

This did fix the issues I was having, thank you.
