### ISSUE TITLE
Option to use custom PBO file icons

### ISSUE THREAD

**Issue by Ferdilanz** [winseros/pboman3#37]
I just had to unpack and repack 157 PBO files which the old PBO Manager 1.4b was unable to do in bulk. I have used that program for so long that I instinctively associate the red archive folder with PBO files. I would like the option to change the file icon so I can still use the instantly recognizable one I have used for so long.

**Comment by winseros** [comment]
Hi, there is no need for a dedicated feature here. You may change the file icon by hand through the Windows registry.

If you have installed the application with the installer, you will find the PBO file icon at the HKEY_CLASSES_ROOT\pboman3_pbo\DefaultIcon`. There you may set it to whatever you need. Just don't forget to reset the system thumbnail cache after you change the icon path in the registry.

![image](https://github.com/winseros/pboman3/assets/6763540/bb63e889-1d9e-4df8-9f5f-4dcdf1e85932)

**Comment by Ferdilanz** [comment]
That worked, thanks a bunch! Say, what's the 1 after the filepath supposed to do? Can I leave it out after changing the path to the ICO file?

**Comment by winseros** [comment]
`,1` is the ID of the icon inside the exe. An executable may contain so called `resources`. Icons - one of the possible resource types. The syntax `app.exe, 1` means _"take the icon with the id=1 from the executable"_.

You can view the resources of an executable using, for example, the [Resource Hacker](https://en.wikipedia.org/wiki/Resource_Hacker).

**Comment by Ferdilanz** [comment]
Figured as much. Thanks again.
