### ISSUE TITLE
Overwrite existing PBO when packing

### ISSUE THREAD

**Issue by genjonakasone** [winseros/pboman3#40]
Right now PBOMan3 will throw out error if user tries to pack a folder into a PBO which name is already used in the same directory, so it has to be manually removed, the manager window closed and whole packing action repeated. Old PBO Manager could just overwrite the existing PBO and copy the older version as .pbo.old. This was very useful and would love to see the same here.

**Comment by winseros** [comment]
Hi, in the last release [v1.6.0](https://github.com/winseros/pboman3/releases/tag/v1.6.0) I introduced the configuration option for the scenario you describe. Please check the `Options -> Settings...`
