### ISSUE TITLE
Junk filter and empty files

### ISSUE THREAD

**Issue by Cathode88** [winseros/pboman3#41]
I've been working with https://github.com/Vdauphin/HeartsAndMinds/ recently and it uses a empty .sqf file that it will not work without (believe it gets compiled when the mission is being loaded) . 

pboman3 1.6.0 keeps removing this file. We need a setting to disable any junk filter or what ever is removing it. As a workaround I have to keep adding the empty SQF (core/init_common.sqf) manually every time I make any changes.

The most frustrating thing about it is that is not communicated that it gets done, and it is done even when just opening a pbo, replacing one file and saving.

**Comment by winseros** [comment]
Hi, I'll add the option in the next release.

**Comment by winseros** [comment]
Hi, I prepared the preliminary build: https://github.com/winseros/pboman3/actions/runs/6129877600

I will prepare a release later

**Comment by winseros** [comment]
Released in [v1.7.0](https://github.com/winseros/pboman3/releases/tag/v1.7.0)
