### ISSUE TITLE
Can't open a PBO

### ISSUE THREAD

**Issue by ilbinek** [winseros/pboman3#45]
Found a PBO (that most probably includes some kind of DRM and is obfuscated) that I'd love to take a peek into.

Had high hopes for PBOMan3, as it manages to open other obfuscated PBOs, but sadly does not manage with this one.

It starts to open it, CPU util ramps up, RAM usage is slowly increasing. The PBO itself is around 350BM. RAM usage went to about 250BM, which took about half an hour. After that, it got reset and started to slowly climb again.

How could I provide you with the PBO for testing? It's not meant to be shared publicly.

**Comment by winseros** [comment]
Hi, you may contact me in ARMA discord (`from: winse_ `) or by email `win.accuracy@gmail.com`

**Comment by winseros** [comment]
The [v1.8.0](https://github.com/winseros/pboman3/releases/tag/v1.8.0) has been released. It should address the issue.
