### ISSUE TITLE
(Suggestion) Rename previous .pbo to .pbo.bak instead of failing to create pbo.

### ISSUE THREAD

**Issue by Elvensbane** [winseros/pboman3#50]
As the title touches on, it would be nice if the program renamed the previous pbos in the directory instead of just failing to build with an error that it already exists. I understand why that's done, but it would make life easier if I didn't have to erase them to proceed each time.

**Comment by winseros** [comment]
Hi, do these options solve the problem?

![image](https://github.com/winseros/pboman3/assets/6763540/993edcb9-88c5-40b7-bdde-9970bc722a22)

**Comment by Elvensbane** [comment]
Seems those will solve my problem!
